services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    network_mode: host
    volumes:
      - /srv/wg-easy:/etc/wireguard
    environment:
      LANG: en
      PORT: 8082
      WG_PORT: 443
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.69.69.x
      WG_DEFAULT_DNS: 10.0.0.45
    env_file:
      - /srv/envs/wg-easy.env
    deploy:
      resources:
        limits:
          memory: 100M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped