services:
  technitium-dns:
    container_name: technitium-dns
    hostname: technitium-dns
    image: technitium/dns-server:latest
    ports:
      - "8081:5380/tcp"
      - "53:53/udp"
      - "53:53/tcp"
      # - "853:853/tcp" #DNS-over-TLS service
      # - "443:443/udp" #DNS-over-HTTPS service (HTTP/3) USING THIS PORT FOR WIREGUARD
      # - "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
    environment:
      - DNS_SERVER_DOMAIN=dns-server
      - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks
      - DNS_SERVER_ENABLE_BLOCKING=true
      - DNS_SERVER_BLOCK_LIST_URLS= https://big.oisd.nl/
    env_file:
      - /srv/envs/technitium.env

    volumes:
      - /srv/wirehole/technitium:/etc/dns
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped
